// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNA6GthXmPlZIoXLc7_U2STp-wruFYcPs',
    appId: '1:469755861196:web:ea0adfd5af1cece12b8a69',
    messagingSenderId: '469755861196',
    projectId: 'users-fabaa',
    authDomain: 'users-fabaa.firebaseapp.com',
    storageBucket: 'users-fabaa.appspot.com',
    measurementId: 'G-WQFH99W273',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0hhf-ZVV5yh3Gt4y00aQ97sK3reJZ9NM',
    appId: '1:469755861196:android:6e25a8e56275a30f2b8a69',
    messagingSenderId: '469755861196',
    projectId: 'users-fabaa',
    storageBucket: 'users-fabaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEI4OpGmkmL5-zoHuphvhNgSEuyp18l0c',
    appId: '1:469755861196:ios:b4002ffbb52d08142b8a69',
    messagingSenderId: '469755861196',
    projectId: 'users-fabaa',
    storageBucket: 'users-fabaa.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEI4OpGmkmL5-zoHuphvhNgSEuyp18l0c',
    appId: '1:469755861196:ios:b4002ffbb52d08142b8a69',
    messagingSenderId: '469755861196',
    projectId: 'users-fabaa',
    storageBucket: 'users-fabaa.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNA6GthXmPlZIoXLc7_U2STp-wruFYcPs',
    appId: '1:469755861196:web:de4ae7cec9fb82a52b8a69',
    messagingSenderId: '469755861196',
    projectId: 'users-fabaa',
    authDomain: 'users-fabaa.firebaseapp.com',
    storageBucket: 'users-fabaa.appspot.com',
    measurementId: 'G-NJW6G32PE7',
  );
}
